services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5434:5432
    volumes:
      - pgData:/var/lig/postgresql/pgData
volumes:
  pgData:    
  